#travis-ci continuous integration test set up  
language: python
python:
  - "2.7"
  #- "3.2"  #python 3.2 works (and passes all tests) but covereralls4.0 CI suite no longer supports python 3.2 see https://github.com/praw-dev/praw/pull/532
  #- "3.3"  #works on python 3.3  (passess all test cases), however Travis CI python 3.3 support is now broken.  download stats show < 0.01% of pythond dist using 3.3
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7" 
  - "3.8"
  - "3.9"

# command to install dependencies
install: 
  #- "pip install -U pytest"
  #- "pip install 'coverage<4'"
  - pip install -U pytest pytest-cov 
  - pip install coveralls 
  #- if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install virtualenv==15.2.0; fi 

# command to run tests
script: 
  - python -m py.test
  #- coverage run --source fifostr -m pytest 

#code coverage
after_success:
  - coveralls