#travis-ci continuous integration test set up 
language: python
python:
  - "2.7"
  #- "3.2"  #python 3.2 works (and passes all tests) but covereralls4.0 CI suite no longer supports python 3.2 see https://github.com/praw-dev/praw/pull/532
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
# command to install dependencies
install: 
  #- "pip install -U pytest"
  #- "pip install 'coverage<4'"
  - pip install -U pytest pytest-cov 
  - pip install coveralls 
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install virtualenv==15.2.0 tox==3.1.3; fi
# command to run tests
script: 
  - cd tests
  - pytest
  - coverage run --source fifostr -m pytest 
#code coverage
after_success:
  - coveralls